# 4.1 Exercise on Functions:
Task - 1: Create a Python program that converts between different units of measurement.


In [40]:
def unit_conversion():
    """
    A program that converts between length, weight, and volume units.

    Conversion options:
    - Length: meters to feet, feet to meters
    - Weight: kilograms to pounds, pounds to kilograms
    - Volume: liters to gallons, gallons to liters
    """

    print("\nWelcome to the Unit Converter!")
    print("Choose a conversion type:")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    try:

        choice = int(input("Enter the number of your choice (1-3): "))


        value = float(input("Enter the value to convert: "))
        if choice == 1:
            print("\nChoose the direction of conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = int(input("Enter 1 or 2: "))

            if sub_choice == 1:
                result = value * 3.28084
                print(f"{value} meters = {result:.2f} feet")
            elif sub_choice == 2:
                result = value / 3.28084
                print(f"{value} feet = {result:.2f} meters")
            else:
                print("Invalid choice for length conversion.")

        elif choice == 2:
            print("\nChoose the direction of conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = int(input("Enter 1 or 2: "))

            if sub_choice == 1:
                result = value * 2.20462  #1kg = 2.20462 lbs
                print(f"{value} kg = {result:.2f} lbs")
            elif sub_choice == 2:
                result = value / 2.20462
                print(f"{value} lbs = {result:.2f} kg")
            else:
                print("Invalid choice for weight conversion.")

        elif choice == 3:
            print("\nChoose the direction of conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = int(input("Enter 1 or 2: "))

            if sub_choice == 1:
                result = value * 0.264172  # 1L = 0.264172 gal
                print(f"{value} L = {result:.2f} gallons")
            elif sub_choice == 2:
                result = value / 0.264172
                print(f"{value} gallons = {result:.2f} L")
            else:
                print("Invalid choice for volume conversion.")

        else:
            print("Invalid main choice. Please enter 1, 2, or 3.")

    except ValueError:
        print("Invalid input! Please enter numbers only.")

unit_conversion()



Welcome to the Unit Converter!
Choose a conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter the number of your choice (1-3): 1
Enter the value to convert: 23

Choose the direction of conversion:
1. Meters to Feet
2. Feet to Meters
Enter 1 or 2: 2
23.0 feet = 7.01 meters


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers

In [41]:
def get_numbers():
    """
    Asks the user to input a list of numbers separated by spaces.
    Returns a list of float numbers.
    """
    while True:
        try:
            numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
            if not numbers:
                raise ValueError("The list cannot be empty. Please enter at least one number.")
            return numbers
        except ValueError:
            print("Invalid input! Please enter numeric values separated by spaces.")

def find_sum(numbers):
    """Returns the sum of the list of numbers."""
    return sum(numbers)

def find_average(numbers):
    """Returns the average of the list of numbers."""
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """Returns the maximum number from the list."""
    return max(numbers)

def find_minimum(numbers):
    """Returns the minimum number from the list."""
    return min(numbers)

def main():
    """
    Prompts the user to select a mathematical operation (sum, average, max, min),
    takes a list of numbers as input, performs the selected operation, and displays the result.
    """
    print("\nMathematical Operations Program")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))

        if choice not in [1, 2, 3, 4]:
            print("Invalid choice! Please enter a number between 1 and 4.")
            return

        numbers = get_numbers()

        if choice == 1:
            result = find_sum(numbers)
            print(f"The sum is: {result}")
        elif choice == 2:
            result = find_average(numbers)
            print(f"The average is: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")

    except ValueError:
        print("Invalid input! Please enter a number between 1 and 4.")


main()



Mathematical Operations Program
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 22 22
The sum is: 44.0


# 4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.


In [42]:
def extract_every_other(lst):
    """
    Returns a new list containing every other element from the input list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list with every other element.
    """
    return lst[::2]

input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)

print("Original List:", input_list)
print("Extracted List:", output_list)


Original List: [1, 2, 3, 4, 5, 6]
Extracted List: [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index

In [43]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, starting from index 'start' and ending at index 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): The starting index.
    end (int): The ending index (inclusive).

    Returns:
    list: A sublist from 'start' to 'end'.
    """
    return lst[start:end+1]

input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4

output_list = get_sublist(input_list, start_index, end_index)

print("Original List:", input_list)
print(f"Sublist from index {start_index} to {end_index}:", output_list)


Original List: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing

In [44]:
def reverse_list(lst):
    """
    Returns a reversed list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]  #slicing with step -1 reverses the list

input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)

print("Original List:", input_list)
print("Reversed List:", output_list)


Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [45]:
def remove_first_last(lst):
    """
    Returns a new list with the first and last elements removed.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]  #slicing to remove the first and last elements


input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)

print("Original List:", input_list)
print("Modified List:", output_list)


Original List: [1, 2, 3, 4, 5]
Modified List: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [46]:
def get_first_n(lst, n):
    """
    Returns the first n elements of a list.

    Parameters:
    lst (list): The original list.
    n (int): The number of elements to extract.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]  #slicing to extract first n elements

input_list = [1, 2, 3, 4, 5]
n = 3

output_list = get_first_n(input_list, n)

print("Original List:", input_list)
print(f"First {n} Elements:", output_list)


Original List: [1, 2, 3, 4, 5]
First 3 Elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.



In [47]:
def get_last_n(lst, n):
    """
    Returns the last n elements of a list.

    Parameters:
    lst (list): The original list.
    n (int): The number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]  #slicing to extract the last n elements

input_list = [1, 2, 3, 4, 5]
n = 2

output_list = get_last_n(input_list, n)

print("Original List:", input_list)
print(f"Last {n} Elements:", output_list)


Original List: [1, 2, 3, 4, 5]
Last 2 Elements: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.


In [48]:
def reverse_skip(lst):
    """
    Returns a new list containing every second element in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list with elements extracted in reverse order.
    """
    return lst[-2::-2]  #start from second-to-last and move backwards with step -2


input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)

print("Original List:", input_list)
print("Extracted List:", output_list)


Original List: [1, 2, 3, 4, 5, 6]
Extracted List: [5, 3, 1]


#4.3 Exercise on Nested List:


1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.



In [49]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): The nested list.

    Returns:
    list: A flattened version of the list.
    """
    flattened_list = []  #initializing an empty list
    for sublist in lst:
        flattened_list.extend(sublist)  #adding elements of each sublist to the main list
    return flattened_list

input_list = [[1, 2], [3, 4], [5]]
output_list = flatten(input_list)

print("Original Nested List:", input_list)
print("Flattened List:", output_list)


Original Nested List: [[1, 2], [3, 4], [5]]
Flattened List: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.


In [50]:
def access_nested_element(lst, indices):
    """
    Retrieves an element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list (like a table).
    indices (list): The row and column indices.

    Returns:
    The element at the given indices.
    """
    row = indices[0]
    column = indices[1]
    return lst[row][column]

nested_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

indices = [1, 2]

output_element = access_nested_element(nested_list, indices)

print("Nested List:", nested_list)
print(f"Element at indices {indices}:", output_element)


Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).


In [51]:
def sum_nested(lst):
    """
    Recursively calculates the sum of all elements in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers.

    Returns:
    int: The sum of all numbers in the nested list.
    """
    total = 0

    for element in lst:
        if isinstance(element, list):  #if the element is a list, call the function recursively
            total += sum_nested(element)
        else:  #if the element is a number, add it to total
            total += element

    return total


nested_list = [[1, 2], [3, [4, 5]], 6]
output_sum = sum_nested(nested_list)

print("Nested List:", nested_list)
print("Sum of all elements:", output_sum)


Nested List: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.


In [65]:
def remove_element(lst, elem):
    """
    Recursively removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to remove.

    Returns:
    list: A new list with the specified element removed.
    """
    new_list = []

    for item in lst:
        if isinstance(item, list):
            filtered_sublist = remove_element(item, elem)
            if filtered_sublist:
                new_list.append(filtered_sublist)
        elif item != elem:
            new_list.append(item)

    return new_list


nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2

output_list = remove_element(nested_list, element_to_remove)

print("Original Nested List:", nested_list)
print(f"Nested List after removing {element_to_remove}:", output_list)


Original Nested List: [[1, 2], [3, 2], [4, 5]]
Nested List after removing 2: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).


In [66]:
def find_max(lst):
    """
    Recursively finds the maximum element in a nested list.

    Parameters:
    lst (list): The nested list containing numbers.

    Returns:
    int/float: The maximum number found in the nested list.
    """
    max_value = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)

    return max_value


nested_list = [[1, 2], [3, [4, 5]], 6]
output_max = find_max(nested_list)

print("Nested List:", nested_list)
print("Maximum Element:", output_max)


Nested List: [[1, 2], [3, [4, 5]], 6]
Maximum Element: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.


In [52]:
def count_occurrences(lst, elem):
    """
    Recursively counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to count.

    Returns:
    int: The number of occurrences of elem in the nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count


nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2

output_count = count_occurrences(nested_list, element_to_count)

print("Nested List:", nested_list)
print(f"Occurrences of {element_to_count}:", output_count)


Nested List: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.


In [53]:
def deep_flatten(lst):
    """
    Recursively flattens a deeply nested list into a single list.

    Parameters:
    lst (list): A deeply nested list.

    Returns:
    list: A single flattened list containing all elements.
    """
    flattened_list = []

    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(deep_flatten(item))
        else:
            flattened_list.append(item)

    return flattened_list


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output_list = deep_flatten(nested_list)

print("Original Nested List:", nested_list)
print("Flattened List:", output_list)


Original Nested List: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.


In [54]:
def average_nested(lst):
    """
    Recursively calculates the average of all elements in a nested list.

    Parameters:
    lst (list): A nested list containing numbers.

    Returns:
    float: The average of all elements in the nested list.
    """
    def flatten(lst):
        """Helper function to flatten the nested list into a single list."""
        flattened_list = []
        for item in lst:
            if isinstance(item, list):
                flattened_list.extend(flatten(item))
            else:
                flattened_list.append(item)
        return flattened_list

    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
output_average = average_nested(nested_list)

print("Nested List:", nested_list)
print("Average of all elements:", output_average)


Nested List: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


#10 To - Do - NumPy


10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:


In [55]:
import numpy as np

In [56]:
empty_array = np.empty((2, 2)) # empty array with size 2x2
print("1. Empty Array (2x2):\n", empty_array)

ones_array = np.ones((4, 2)) #array with size 4x2
print("\n2. Ones Array (4x2):\n", ones_array)

fill_array = np.full((3, 3), 7)
print("\n3. Filled Array (3x3) with 7:\n", fill_array)

reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\n4. Zeros Array (Same shape as reference array):\n", zeros_like_array)

ones_like_array = np.ones_like(reference_array)
print("\n5. Ones Array (Same shape as reference array):\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array from list:\n", numpy_array)

1. Empty Array (2x2):
 [[1.93986388e-316 0.00000000e+000]
 [9.51299973e+077 1.68199888e+199]]

2. Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array (3x3) with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Array (Same shape as reference array):
 [[0 0]
 [0 0]]

5. Ones Array (Same shape as reference array):
 [[1 1]
 [1 1]]

6. Converted NumPy Array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:


In [57]:
array_range = np.arange(10, 50) #array with values ranging from 10 to 49
print("1. Array with values from 10 to 49:\n", array_range)

matrix_3x3 = np.arange(9).reshape(3, 3) #3x3 matrix with values ranging from 0 to 8
print("\n2. 3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

identity_matrix = np.eye(3) #3x3 identity matrix
print("\n3. 3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30) #random array of size 30 and find the mean
mean_value = random_array.mean()
print("\n4. Mean of a random array of size 30:\n", mean_value)

random_10x10 = np.random.random((10, 10)) #10x10 array with random values and find min and max
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. Min and Max of a 10x10 Random Array:\nMin:", min_value, "Max:", max_value)

zero_array = np.zeros(10) #zero array of size 10 and replace 5th element with 1
zero_array[4] = 1
print("\n6. Zero Array with 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:\n", reversed_arr)

border_array = np.ones((5, 5)) #2D array with 1 on border and 0 inside
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on Border and 0 Inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int) #8x8 matrix and fill it with a checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)


1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of a random array of size 30:
 0.5141166245921291

5. Min and Max of a 10x10 Random Array:
Min: 0.0014764355074091684 Max: 0.9968250206664633

6. Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. 2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:



In [58]:

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition_result = x + y
print("1. Addition of x and y:\n", addition_result)

subtraction_result = x - y
print("\n2. Subtraction of x and y:\n", subtraction_result)

multiplication_result = x * 2
print("\n3. Multiplication of x by 2:\n", multiplication_result)

square_result = np.square(x)
print("\n4. Square of each element in x:\n", square_result)


dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot Product Results:")
print("v ⋅ w:", dot_vw)
print("x ⋅ v:\n", dot_xv)
print("x ⋅ y:\n", dot_xy)


concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_cols = np.vstack((v, w))
print("\n6. Concatenation of x and y along rows:\n", concat_xy_rows)
print("\nConcatenation of v and w along columns:\n", concat_vw_cols)


try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. Error when trying to concatenate x and v:", e)


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot Product Results:
v ⋅ w: 219
x ⋅ v:
 [29 77]
x ⋅ y:
 [[19 22]
 [50 58]]

6. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

7. Error when trying to concatenate x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

In [59]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)  #computing inverse of A
identity_matrix = np.dot(A, A_inv)

print("1. Proof that A * A^-1 = I:\n", np.round(identity_matrix, decimals=4))  #np.round to avoid floating-point errors

#2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)  #
print("\n2. Proof that AB ≠ BA:\nAB:\n", AB, "\nBA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)  # (AB)^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))  # B^T A^T
print("\n3. Proof that (AB)^T = B^T A^T:\n(AB)^T:\n", AB_T, "\nB^T A^T:\n", BT_AT)

"""4. Solve System of Linear Equations using Inverse Method
System of equations:
2x - 3y +  z = -1
x  -  y + 2z = -3
3x +  y -  z =  9"""

# Represent as AX = B
A_eq = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B_eq = np.array([-1, -3, 9])

#solving using np.linalg.inv()
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)

print("\n4. Solution to the system of linear equations:\n[x, y, z] =\n", X)

1. Proof that A * A^-1 = I:
 [[1. 0.]
 [0. 1.]]

2. Proof that AB ≠ BA:
AB:
 [[23 13]
 [51 29]] 
BA:
 [[36 44]
 [13 16]]

3. Proof that (AB)^T = B^T A^T:
(AB)^T:
 [[23 51]
 [13 29]] 
B^T A^T:
 [[23 51]
 [13 29]]

4. Solution to the system of linear equations:
[x, y, z] =
 [ 2.  1. -2.]


#10.2 Experiment: How Fast is Numpy?


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [60]:
import time

In [61]:
#two lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

In [62]:
#measuring time for Python list addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
python_time = end_time - start_time
print(f"1. Time taken for Python List Addition: {python_time:.6f} seconds")

#two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

#measureing time for NumPy array addition
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"2. Time taken for NumPy Array Addition: {numpy_time:.6f} seconds")

#compare performance
speedup = python_time / numpy_time
print(f"\nNumPy is approximately {speedup:.2f} times faster than Python Lists.")

1. Time taken for Python List Addition: 0.136493 seconds
2. Time taken for NumPy Array Addition: 0.005884 seconds

NumPy is approximately 23.20 times faster than Python Lists.


2. Element-wise Multiplication



In [63]:

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
python_time = end_time - start_time
print(f"1. Time taken for Python List Multiplication: {python_time:.6f} seconds")

#two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

#time for NumPy array multiplication
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"2. Time taken for NumPy Array Multiplication: {numpy_time:.6f} seconds")


speedup = python_time / numpy_time
print(f"\nNumPy is approximately {speedup:.2f} times faster than Python Lists.")

1. Time taken for Python List Multiplication: 0.127443 seconds
2. Time taken for NumPy Array Multiplication: 0.002617 seconds

NumPy is approximately 48.70 times faster than Python Lists.


3. Dot Product

In [64]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
python_time = end_time - start_time
print(f"1. Time taken for Python List Dot Product: {python_time:.6f} seconds")

#two NumPy arrays of size 1,000,000
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

#time for NumPy array dot product
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"2. Time taken for NumPy Array Dot Product: {numpy_time:.6f} seconds")


speedup = python_time / numpy_time
print(f"\nNumPy is approximately {speedup:.2f} times faster than Python Lists.")

1. Time taken for Python List Dot Product: 0.103340 seconds
2. Time taken for NumPy Array Dot Product: 0.001946 seconds

NumPy is approximately 53.10 times faster than Python Lists.


4. Matrix Multiplication

In [39]:


#matrix size
N = 1000

#two 1000x1000 matrices using Python lists
list1 = [[i * j for j in range(N)] for i in range(N)]
list2 = [[j * i for j in range(N)] for i in range(N)]

#time for Python list matrix multiplication
start_time = time.time()
result_list = [[sum(list1[i][k] * list2[k][j] for k in range(N)) for j in range(N)] for i in range(N)]
end_time = time.time()
python_time = end_time - start_time
print(f"1. Time taken for Python List Matrix Multiplication: {python_time:.6f} seconds")

#two 1000x1000 matrices using NumPy
array1 = np.arange(N * N).reshape(N, N)
array2 = np.arange(N * N).reshape(N, N)

#time for NumPy matrix multiplication
start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"2. Time taken for NumPy Array Matrix Multiplication: {numpy_time:.6f} seconds")


speedup = python_time / numpy_time
print(f"\nNumPy is approximately {speedup:.2f} times faster than Python Lists.")


1. Time taken for Python List Matrix Multiplication: 224.831834 seconds
2. Time taken for NumPy Array Matrix Multiplication: 1.943081 seconds

NumPy is approximately 115.71 times faster than Python Lists.
